/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import ups.edu.ec.controlador.ControladorTelefono;
import ups.edu.ec.controlador.ControladorUsuario;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {


    private ControladorUsuario controladorUsuario;
    private ControladorTelefono controladorTelefono;
    private VentanaCrearUsuario ventanaRegistrarUsuario;
    private VentanaIniciarSesion ventanaIniciarSesion;
    private VentanaRegistrarTelefono ventanaRegistrarTelefono;
    private VentanaTelefono ventanaTelefono;
    private VentanaUsuario ventanaUsuario;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        controladorUsuario = new ControladorUsuario();
        controladorTelefono = new ControladorTelefono();

        ventanaTelefono = new VentanaTelefono(controladorUsuario, controladorTelefono);
        ventanaUsuario = new VentanaUsuario(controladorUsuario);
        ventanaRegistrarUsuario = new VentanaCrearUsuario(controladorUsuario);
        ventanaIniciarSesion = new VentanaIniciarSesion(controladorUsuario, this,ventanaTelefono, ventanaUsuario);
        ventanaRegistrarTelefono = new VentanaRegistrarTelefono(controladorUsuario,controladorTelefono);
        

        jDesktopPane1.add(ventanaRegistrarUsuario);
        jDesktopPane1.add(ventanaIniciarSesion);
        jDesktopPane1.add(ventanaRegistrarTelefono);
        jDesktopPane1.add(ventanaTelefono);
        jDesktopPane1.add(ventanaUsuario);

        this.setExtendedState(VentanaPrincipal.MAXIMIZED_BOTH);
    }
    
    public JMenu getMenuGestion() {
        return jMenu2;
    }

    public JMenuItem getMenuItemCerrarSesion() {
        return menuItemCerrarSesion;
    }

    public JMenuItem getMenuItemCrearUsuario() {
        return menuItemCrearUsuario;
    }

    public JMenuItem getMenuItemIniciarSesion() {
        return menuItemIniciarSesion;
    }

    public void cerrarVentanas() {
        ventanaRegistrarUsuario.setVisible(false);
        ventanaIniciarSesion.setVisible(false);
        ventanaRegistrarTelefono.setVisible(false);
        ventanaTelefono.setVisible(false);
        ventanaUsuario.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        menuItemCrearUsuario = new javax.swing.JMenuItem();
        menuItemIniciarSesion = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemTelefono = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemGestionUsuario = new javax.swing.JMenuItem();
        menuItemGestionTelefonos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jMenu.setText("Menú");

        menuItemCrearUsuario.setText("Crear Usuario");
        menuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu.add(menuItemCrearUsuario);

        menuItemIniciarSesion.setText("Iniciar Sesión");
        menuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarSesionActionPerformed(evt);
            }
        });
        jMenu.add(menuItemIniciarSesion);

        menuItemCerrarSesion.setText("Cerrar Sesión");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu.add(menuItemCerrarSesion);

        menuItemTelefono.setText("Teléfonos");
        menuItemTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTelefonoActionPerformed(evt);
            }
        });
        jMenu.add(menuItemTelefono);

        menuItemExit.setText("Salir");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu.add(menuItemExit);

        menuBar.add(jMenu);

        jMenu2.setText("Gestión");

        menuItemGestionUsuario.setText("Usuario");
        menuItemGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGestionUsuario);

        menuItemGestionTelefonos.setText("Teléfonos");
        menuItemGestionTelefonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionTelefonosActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGestionTelefonos);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearUsuarioActionPerformed
        cerrarVentanas();
        ventanaRegistrarUsuario.setVisible(true);
    }//GEN-LAST:event_menuItemCrearUsuarioActionPerformed

    private void menuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarSesionActionPerformed
        cerrarVentanas();
        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_menuItemIniciarSesionActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
       cerrarVentanas();
        jMenu2.setEnabled(false);
        menuItemCerrarSesion.setEnabled(false);
        menuItemCrearUsuario.setEnabled(true);
        menuItemIniciarSesion.setEnabled(true);
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTelefonoActionPerformed
        cerrarVentanas();
        ventanaRegistrarTelefono.setVisible(true);
    }//GEN-LAST:event_menuItemTelefonoActionPerformed

    private void menuItemGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionUsuarioActionPerformed
        cerrarVentanas();
        ventanaUsuario.setVisible(true);
    }//GEN-LAST:event_menuItemGestionUsuarioActionPerformed

    private void menuItemGestionTelefonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionTelefonosActionPerformed
        cerrarVentanas();
        ventanaTelefono.setVisible(true);
    }//GEN-LAST:event_menuItemGestionTelefonosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemCrearUsuario;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemGestionTelefonos;
    private javax.swing.JMenuItem menuItemGestionUsuario;
    private javax.swing.JMenuItem menuItemIniciarSesion;
    private javax.swing.JMenuItem menuItemTelefono;
    // End of variables declaration//GEN-END:variables
}
