/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ups.edu.ec.controlador.ControladorTelefono;
import ups.edu.ec.controlador.ControladorUsuario;
import ups.edu.ec.modelo.*;

/**
 *
 * @author Usuario
 */
public class VentanaRegistrarTelefono extends javax.swing.JInternalFrame {
    private ControladorUsuario controladorUsuario;
    private ControladorTelefono controladorTelefono;
    
    /**
     * Creates new form VentanaRegistrarTelefono
     * @param controladorUsuario
     * @param controladorTelefono
     */
    public VentanaRegistrarTelefono(ControladorUsuario controladorUsuario, 
            ControladorTelefono controladorTelefono) {
        initComponents();
        comboOpc.setSelectedIndex(0);
        this.controladorUsuario = controladorUsuario;
        this.controladorTelefono = controladorTelefono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboOpc = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JFormattedTextField();
        txtBusquedaApellido = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTelf = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Buscar Por:");

        comboOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Apellido", "Cédula", "Celular", "Casa" }));
        comboOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOpcActionPerformed(evt);
            }
        });

        txtBusqueda.setEditable(false);

        txtBusquedaApellido.setEditable(false);

        btnListar.setText("Listar Todo");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Cédula:");

        jLabel5.setText("Correo:");

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        txtCedula.setEditable(false);

        txtCorreo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(comboOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar)
                            .addComponent(btnBuscar))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBusqueda)
                            .addComponent(txtBusquedaApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboOpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        tblTelf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Número", "Tipo", "Operadora"
            }
        ));
        jScrollPane1.setViewportView(tblTelf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        var listaTelefono = (List<Telefono>) controladorTelefono.findAll();

        if (listaTelefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen teléfonos");
        } else {
            llenarTabla(listaTelefono);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String itemSeleccionado = (String) comboOpc.getSelectedItem();

        if (itemSeleccionado.equalsIgnoreCase("Apellido")) {
            String busquedaTexto = txtBusquedaApellido.getText();
            System.out.println(busquedaTexto);

            String[] apellidos = busquedaTexto.split(" ");
            String apellidoMayusculas = "";
            for (String apellido : apellidos) {
                apellidoMayusculas += String.valueOf(Character.toUpperCase(apellido.charAt(0)));
                apellidoMayusculas += apellido.substring(1, apellido.length()).toLowerCase();
                apellidoMayusculas += " ";
            }           
            
            Usuario usuario = new Usuario(apellidoMayusculas.trim());
            usuario = (Usuario) controladorUsuario.read(usuario);
            if (usuario != null) {

                txtNombre.setText(usuario.getNombre());
                txtApellido.setText(usuario.getApellido());
                txtCedula.setText(usuario.getCedula());
                txtCorreo.setText(usuario.getCorreo());

                if (!usuario.getListaTelefonos().isEmpty()) {
                    llenarTabla(usuario.getListaTelefonos());
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario no registra teléfonos");
                }
            } else {
                //limpiarDatos();
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }

        } else if (itemSeleccionado.equalsIgnoreCase("Cédula")) {
            String busquedaTexto = String.valueOf(txtBusqueda.getValue());
            System.out.println(busquedaTexto);
            Usuario usuario = new Usuario();
            usuario.setCedula(busquedaTexto.trim());
            usuario = (Usuario) controladorUsuario.readCedula(usuario);
            if (usuario != null) {

                txtNombre.setText(usuario.getNombre());
                txtApellido.setText(usuario.getApellido());
                txtCedula.setText(usuario.getCedula());
                txtCorreo.setText(usuario.getCorreo());

                if (!usuario.getListaTelefonos().isEmpty()) {
                    llenarTabla(usuario.getListaTelefonos());
                } else {
                    JOptionPane.showMessageDialog(this, "El usuario no registra teléfonos");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }

        } else {
            String busquedaTexto = String.valueOf(txtBusqueda.getValue());
            System.out.println(busquedaTexto);
            Telefono telefono = new Telefono(busquedaTexto.trim());
            telefono = (Telefono) controladorTelefono.read(telefono);
            if (telefono != null) {
                telefono.toString();

                var usuario = controladorUsuario.readNumero(telefono);
                if (usuario != null) {
                    txtNombre.setText(usuario.getNombre());
                    txtApellido.setText(usuario.getApellido());
                    txtCedula.setText(usuario.getCedula());
                    txtCorreo.setText(usuario.getCorreo());

                    DefaultTableModel modeloTabla = (DefaultTableModel) tblTelf.getModel();
                    modeloTabla.setRowCount(0);
                    Object[] rowData = {telefono.getCodigo(), telefono.getNumero(), telefono.getTipo(), telefono.getOperadora()};
                    modeloTabla.addRow(rowData);
                    tblTelf.setModel(modeloTabla);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Teléfono no encontrado");
            }
        }

    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void comboOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOpcActionPerformed
       try {
            String item = (String) comboOpc.getSelectedItem();
            if (item.equals("Apellido")) {
                txtBusquedaApellido.setEnabled(true);
                txtBusquedaApellido.setEditable(true);
                txtBusqueda.setEnabled(false);
                btnListar.setEnabled(false);
                btnBuscar.setEnabled(true);


            } else if (item.equals("Celular")) {
                formatearOpcion();
                txtBusquedaApellido.setText("");
                txtBusqueda.setFormatterFactory(
                        new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.MaskFormatter("(593)0##-###-####")
                        )
                );

            } else if (item.equals("Casa")) {
                formatearOpcion();
                txtBusquedaApellido.setText("");
                txtBusqueda.setFormatterFactory(
                        new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.MaskFormatter("(593)0#-####-###")
                        )
                );

            } else if (item.equals("Cédula")) {
                formatearOpcion();

                txtBusquedaApellido.setText("");
                txtBusqueda.setFormatterFactory(
                        new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.MaskFormatter("##########")
                        )
                );
            } else {
                txtBusquedaApellido.setText("");
                txtBusqueda.setEditable(false);
                txtBusqueda.setEnabled(false);
                txtBusquedaApellido.setEditable(false);
                txtBusquedaApellido.setEnabled(false);
                txtBusqueda.setBackground(Color.DARK_GRAY);
                btnBuscar.setEnabled(false);
                btnListar.setEnabled(true);

                txtBusqueda.setFormatterFactory(
                        new javax.swing.text.DefaultFormatterFactory(
                                new javax.swing.text.MaskFormatter("")
                        )
                );
            }
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato del teléfono erroneo");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_comboOpcActionPerformed
    public void limpiar() {
        comboOpc.setSelectedIndex(0);
        txtBusqueda.setValue("");
        txtBusquedaApellido.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtCorreo.setText("");

        DefaultTableModel modeloTabla = (DefaultTableModel) tblTelf.getModel();
        modeloTabla.setRowCount(0);
        tblTelf.setModel(modeloTabla);

        btnBuscar.setEnabled(false);
        btnListar.setEnabled(true);

    }

    public void limpiarDatos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtCorreo.setText("");

        DefaultTableModel modeloTabla = (DefaultTableModel) tblTelf.getModel();
        modeloTabla.setRowCount(0);
        tblTelf.setModel(modeloTabla);

        btnBuscar.setEnabled(false);
        btnListar.setEnabled(true);
    }

    public void formatearOpcion() {
        txtBusqueda.setEditable(true);
        txtBusqueda.setValue("");
        txtBusqueda.setEnabled(true);
        txtBusqueda.setBackground(Color.white);
        btnListar.setEnabled(false);
        btnBuscar.setEnabled(true);
        txtBusquedaApellido.setEnabled(false);

    }

    public void llenarTabla(List<Telefono> listaTelefonos) {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblTelf.getModel();
        modeloTabla.setRowCount(0);

        for (Telefono tlf : listaTelefonos) {
            Object[] rowData = {tlf.getCodigo(), tlf.getNumero(), tlf.getTipo(), tlf.getOperadora()};
            modeloTabla.addRow(rowData);
        }

        tblTelf.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> comboOpc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTelf;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedaApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
