/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAutoridadCivil;
import ec.edu.ups.controlador.ControladorMatrimonio;
import ec.edu.ups.controlador.ControladorPersona;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaIniciarSesion ventanaIniciarSesion;
    private VentanaGestionPersona ventanaGestionPersona;
    private VentanaMatrimonio ventanaMatrimonio;
    private VentanaCrearAutoridad ventanaCrearAutoridad;
    private VentanaGestionAutoridad ventanaGestionAutoridad;
    
    private ControladorPersona controladorPersona;
    private ControladorAutoridadCivil controladorAutoridadCivil;
    private ControladorMatrimonio controladorMatrimonio;
    
    public VentanaPrincipal() {
        initComponents();
        gestionMenu.setVisible(false);
        cerrarSesionMenu.setVisible(false);
        controladorPersona= new ControladorPersona();
        controladorAutoridadCivil=new ControladorAutoridadCivil();
        controladorMatrimonio = new ControladorMatrimonio();
        
        ventanaIniciarSesion = new VentanaIniciarSesion(this,controladorAutoridadCivil);
        ventanaGestionPersona = new VentanaGestionPersona(controladorPersona);
     /*   ventanaMatrimonio = new VentanaMatrimonio();
        ventanaGestionAutoridad = new VentanaGestionAutoridad();*/
        ventanaCrearAutoridad = new VentanaCrearAutoridad(controladorAutoridadCivil);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        inicioMenu = new javax.swing.JMenu();
        crearAutoridadMenu = new javax.swing.JMenuItem();
        iniciarSesionMenu = new javax.swing.JMenuItem();
        cerrarSesionMenu = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenuItem();
        gestionMenu = new javax.swing.JMenu();
        gestionPesonaMenu = new javax.swing.JMenuItem();
        gestionAutoridadMenu = new javax.swing.JMenuItem();
        matrimonioMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        inicioMenu.setMnemonic('f');
        inicioMenu.setText("Inicio");

        crearAutoridadMenu.setMnemonic('o');
        crearAutoridadMenu.setText("Crear Autoridad");
        crearAutoridadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAutoridadMenuActionPerformed(evt);
            }
        });
        inicioMenu.add(crearAutoridadMenu);

        iniciarSesionMenu.setMnemonic('s');
        iniciarSesionMenu.setText("Iniciar Sesión");
        iniciarSesionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionMenuActionPerformed(evt);
            }
        });
        inicioMenu.add(iniciarSesionMenu);

        cerrarSesionMenu.setMnemonic('a');
        cerrarSesionMenu.setText("Cerrar Sesión");
        cerrarSesionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionMenuActionPerformed(evt);
            }
        });
        inicioMenu.add(cerrarSesionMenu);

        salirMenu.setMnemonic('x');
        salirMenu.setText("Salir");
        salirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuActionPerformed(evt);
            }
        });
        inicioMenu.add(salirMenu);

        menuBar.add(inicioMenu);

        gestionMenu.setMnemonic('e');
        gestionMenu.setText("Gestión");

        gestionPesonaMenu.setMnemonic('t');
        gestionPesonaMenu.setText("Gestionar Persona");
        gestionPesonaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPesonaMenuActionPerformed(evt);
            }
        });
        gestionMenu.add(gestionPesonaMenu);

        gestionAutoridadMenu.setMnemonic('y');
        gestionAutoridadMenu.setText("Gestionar Autoridad");
        gestionAutoridadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAutoridadMenuActionPerformed(evt);
            }
        });
        gestionMenu.add(gestionAutoridadMenu);

        matrimonioMenu.setMnemonic('p');
        matrimonioMenu.setText("Acta de Matrimonio");
        matrimonioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrimonioMenuActionPerformed(evt);
            }
        });
        gestionMenu.add(matrimonioMenu);

        menuBar.add(gestionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuActionPerformed

    private void crearAutoridadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAutoridadMenuActionPerformed
        desktopPane.add(ventanaCrearAutoridad);
        ventanaCrearAutoridad.setVisible(true);
    }//GEN-LAST:event_crearAutoridadMenuActionPerformed

    private void iniciarSesionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionMenuActionPerformed
        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_iniciarSesionMenuActionPerformed

    private void cerrarSesionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionMenuActionPerformed
        iniciarSesionMenu.setVisible(true);
        crearAutoridadMenu.setVisible(true);
        gestionMenu.setVisible(false);
        salirMenu.setVisible(true);
    }//GEN-LAST:event_cerrarSesionMenuActionPerformed

    private void gestionPesonaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPesonaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionPesonaMenuActionPerformed

    private void gestionAutoridadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAutoridadMenuActionPerformed
        desktopPane.add(ventanaGestionPersona);
        ventanaGestionPersona.setVisible(true);
    }//GEN-LAST:event_gestionAutoridadMenuActionPerformed

    private void matrimonioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrimonioMenuActionPerformed
        desktopPane.add(ventanaMatrimonio);
       ventanaMatrimonio.setVisible(true);
    }//GEN-LAST:event_matrimonioMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public JMenuItem getCerrarSesionMenu() {
        return cerrarSesionMenu;
    }

    public void setCerrarSesionMenu(JMenuItem cerrarSesionMenu) {
        this.cerrarSesionMenu = cerrarSesionMenu;
    }

    public JMenuItem getCrearAutoridadMenu() {
        return crearAutoridadMenu;
    }

    public void setCrearAutoridadMenu(JMenuItem crearAutoridadMenu) {
        this.crearAutoridadMenu = crearAutoridadMenu;
    }

    public JMenuItem getGestionAutoridadMenu() {
        return gestionAutoridadMenu;
    }

    public void setGestionAutoridadMenu(JMenuItem gestionAutoridadMenu) {
        this.gestionAutoridadMenu = gestionAutoridadMenu;
    }

    public JMenu getGestionMenu() {
        return gestionMenu;
    }

    public void setGestionMenu(JMenu gestionMenu) {
        this.gestionMenu = gestionMenu;
    }

    public JMenuItem getGestionPesonaMenu() {
        return gestionPesonaMenu;
    }

    public void setGestionPesonaMenu(JMenuItem gestionPesonaMenu) {
        this.gestionPesonaMenu = gestionPesonaMenu;
    }

    public JMenuItem getIniciarSesionMenu() {
        return iniciarSesionMenu;
    }

    public void setIniciarSesionMenu(JMenuItem iniciarSesionMenu) {
        this.iniciarSesionMenu = iniciarSesionMenu;
    }

    public JMenu getInicioMenu() {
        return inicioMenu;
    }

    public void setInicioMenu(JMenu inicioMenu) {
        this.inicioMenu = inicioMenu;
    }

    public JMenuItem getMatrimonioMenu() {
        return matrimonioMenu;
    }

    public void setMatrimonioMenu(JMenuItem matrimonioMenu) {
        this.matrimonioMenu = matrimonioMenu;
    }

    public JMenuItem getSalirMenu() {
        return salirMenu;
    }

    public void setSalirMenu(JMenuItem salirMenu) {
        this.salirMenu = salirMenu;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesionMenu;
    private javax.swing.JMenuItem crearAutoridadMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem gestionAutoridadMenu;
    private javax.swing.JMenu gestionMenu;
    private javax.swing.JMenuItem gestionPesonaMenu;
    private javax.swing.JMenuItem iniciarSesionMenu;
    private javax.swing.JMenu inicioMenu;
    private javax.swing.JMenuItem matrimonioMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem salirMenu;
    // End of variables declaration//GEN-END:variables

}
