/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAutoridadCivil;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class VentanaIniciarSesion extends javax.swing.JInternalFrame {

    private VentanaPrincipal ventanaPrincipal;
    private ControladorAutoridadCivil controladorAutoridad;

   

    /**
     * Creates new form VentanaIniciarSesion
     */
    public VentanaIniciarSesion(VentanaPrincipal ventanaPrincipal,ControladorAutoridadCivil controladorAutoridad ) {
        initComponents();
       this.ventanaPrincipal=ventanaPrincipal;
       this.controladorAutoridad= controladorAutoridad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnIniciarS = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();

        jLabel1.setText("Correo Electrónico:");

        jLabel2.setText("Contraseña:");

        txtCorreo.setToolTipText("");

        btnIniciarS.setText("Iniciar Sesión");
        btnIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel3.setText("Iniciar Sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtPwd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnIniciarS)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarS)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSActionPerformed
        String autoridad = txtCorreo.getText();
        String contrasenia = "";
        char[] contrasenia1 = txtPwd.getPassword();
        for (int i = 0; i < contrasenia1.length; i++) {
            contrasenia = contrasenia + contrasenia1[i];
        }

        if (controladorAutoridad.iniciarSesion(autoridad, contrasenia)) {
            ventanaPrincipal.getIniciarSesionMenu().setVisible(false);
            ventanaPrincipal.getCerrarSesionMenu().setVisible(true);
            ventanaPrincipal.getGestionMenu().setVisible(true);
            
            ventanaPrincipal.getSalirMenu().setVisible(false);
            ventanaPrincipal.getGestionPesonaMenu().setVisible(false);
            ventanaPrincipal.getGestionMenu().setVisible(true);

            this.dispose();
            JOptionPane.showMessageDialog(this, "Inicio de sesion exitoso");
        } else {
            
            JOptionPane.showMessageDialog(this, "Usuario o contrasena incorrecta ");
            Limpiar();
        }
    }//GEN-LAST:event_btnIniciarSActionPerformed
    public void Limpiar() {
        txtCorreo.setText("");
        txtPwd.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarS;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables
}
